---
title: "CV"
author: "Gaetano Scaduto"
output:
  pdf_document:
    latex_engine: pdflatex
    template: "C:/Users/100722gsc/OneDrive - Erasmus University Rotterdam/Dottorato/CV/cv/svm-latex-cv.tex"
  html_document:
    df_print: paged
geometry: margin=1.1in
jobtitle: Postdoctoral Researcher 
born: Born Feb 25th, 1999 in Agrigento, Italy  
fontawesome: yes
#email: gaetano.scaduto@unimib.it
web: "gaetanoscaduto.quarto.pub/home/"
#github: "github.com/gaetanoscaduto"
address: Currently residing in Antwerp, Belgium
#updated: yes
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 10pt
linkcolor: blue
urlcolor: blue
---

<!-- -->

# Appointments

## Postdoctoral Researcher \hfill Oct 2025-Present

*Erasmus University Rotterdam*. Rotterdam. The Netherlands.

-   Erasmus School of Social and Behavioural Sciences, Department of Public Administration and Sociology (DPAS), Governance and Pluralism.
-   Working on the project [CLIMEANING](https://www.nwo.nl/en/projects/domyz32585) (PI: Willem De Koster).

## Thesis Supervisor \hfill Mar 2026-Present

*Erasmus University Rotterdam*. Rotterdam. The Netherlands.

-   Erasmus School of Social and Behavioural Sciences, Department of Psychology, Education, and Child Studies (DPECS).
-   First supervisor of 13 bachelor theses.

## (Voluntary) Fellow \hfill Sep 2025-Present

*University of Antwerp*, Antwerp, Belgium.

-   Faculty of Social Sciences, Department of Political Science.
-   Collaborating in the activities of the ["Media, Movement and Politics" (M2P)](https://www.uantwerpen.be/en/research-groups/m2p/) research group and the [NOTLIKEUS](https://notlikeus.be/) project.

## Visiting Fellow \hfill Mar 2026-Apr 2026

*Collegio Carlo Alberto*, Turin, Italy.

<!-- -->

## Teaching Assistant in Public Policies \hfill Oct 2023-Sep 2025

*University of Milan-Bicocca*, Milan, Italy

-   BS in Organization Sciences
-   More than 16 hours of in-class teaching, in addition to other duties

## Teaching Assistant in Mathematics \hfill Nov 2023-Sep 2025

*University of Milan-Bicocca*, Milan, Italy

-   BS in Organization Sciences
-   More than 16 hours of in-class teaching, in addition to other duties

\bigskip \hrule

# **Education**

## Ph.D. in Analysis of Social and Economic Processes \hfill Nov 2022-Feb 2026

*University of Milan-Bicocca*, Milan, Italy

-   Supervisors: Fedra Negri (Unimib), Delia Baldassarri (New York University).
-   Thesis title: "Thinking About Politics: An Experimental Inquiry into the Mental Associations between Political and Apolitical Traits and Their Social Consequences in Italy"
-   Final evaluation: Excellent

## Visiting Ph.D. Student \hfill Feb 2024-Aug 2025

*University of Antwerp*, Antwerp, Belgium

-   Supervisor: Stefaan Walgrave
-   Collaborating in the activities of the ["Media, Movement and Politics" (M2P)](https://www.uantwerpen.be/en/research-groups/m2p/) research group and the [NOTLIKEUS](https://notlikeus.be/) project as a visiting researcher during my Ph.D. at the University of Milan Bicocca

## Master's Degree in Political and Public Communication \hfill Sep 2020-Jul 2022

*University of Turin*, Turin, Italy

-   Thesis supervisor: Moreno Mancosu
-   Thesis title: "A country of upbeat songs while there is death outside? Analysis of Italian politicians' visual communication on Instagram during the Covid-19 pandemic"
-   Final grade: 110/110 with honors, special mention, and rights of publication (*dignità di stampa*).

## Bachelor's Degree in Mathematics for Engineering \hfill Sep 2017-Jul 2020

*Polytechnic University of Turin*, Turin, Italy

-   Thesis supervisor: Giacomo Como
-   Thesis title: "Social Choice Theory"
-   Final grade: 110/110

## High School Diploma\hfill Sep 2012-Jul 2017

*Liceo Classico "Empedocle"*, Agrigento, Italy

-   Final grade: 100/100 with honors

\bigskip \hrule

# Summer Schools, Winter Schools, and Short Courses

## The Summer Institutes in Computational Social Science, University of Bologna \hfill  Jun 2024

-   2-week summer school on computational methods, with competitive selection process.
-   Various teachers.

## Essex Summer School in Social Science Data Analysis, University of Essex \hfill  Jul-Aug 2023

-   *Confirmatory Factor Analysis and Structural Equation Modeling* \hfill Essex, UK
-   Teachers: Prof. Peter Schmidt (University of Giessen), & Dr. Daniel Seddig (University of Cologne)

## Essex Summer School in Social Science Data Analysis, University of Essex \hfill  Jul-Aug 2023

-   *Causal Inference and Experiments in Social Sciences* \hfill Essex, UK
-   Teachers: Dr. Ryan T. Moore (American University)

## SISP - Italian Political Science Society \hfill  Sep 2023

-   *Crash Course in Text Analysis* \hfill Genoa, Italy

-   Teachers: Dr. Silvia Decadri (University of Milan)

    \bigskip \hrule

# Publications

## Books

1.   **Scaduto, G.** Thinking About Politics: Political Stereotypes, Projections, and Their Social Consequences in Italy. Book manuscript. *Palgrave Macmillan*. Forthcoming (2027).

## Papers published/accepted in peer-reviewed journals

### 2025

10. **Scaduto, G.**, Negri, F., Decadri, S. It’s the Homophily, Stupid: How Apolitical Similarities Affect Political Conversations. *Political Behavior*. <https://doi.org/10.1007/s11109-025-10102-x>

<!-- -->

9.  **Scaduto, G.** Politicultural Linking: Inferences between Political and Apolitical Traits. *Public Opinion Quarterly*, 89(3). <https://doi.org/10.1093/poq/nfaf047>.

<!-- -->

8.  Decadri, S., Mancosu, M., Negri, F., **Scaduto, G.** Aligning Emotions: A Comparative Analysis of Text and Imagery by European Party Leaders on Instagram. *The International Journal of Press/Politics*. <https://doi.org/10.1177/19401612251339107>

<!-- -->

7.  Respi, C., Gui, M., **Scaduto, G.**, Serini, M., Pizzul, D., Gerosa, T., & Lutz, C. Lower Cynicism, Not Higher Literacy, Promotes Protective Behavior: Exploring the “privacy exception” in the Digital Inequality Framework. *Social Science Computer Review*. <https://doi.org/10.1177/08944393251341201>

### 2024

6.  **Scaduto, G.**, Negri, F. The Pundit Paradox: Exploring the Mismatch between Supply and Demand in Italian Political Talk Show Guests. *Comunicazione Politica.* <https://www.rivisteweb.it/doi/10.3270/115244>

<!-- -->

5.  **Scaduto, G.**, Negri, F. Food for (political) thought: political inferences from apolitical cues and their social consequences in Italy. *South European Society and Politics*. *29*(1), 79-108. <https://doi.org/10.1080/13608746.2024.2411539>

<!-- -->

4.  Mancosu, M., **Scaduto, G.** Crowds and Smiles: Visual Opportunity Structures and the Communication of European Political Leaders During the COVID-19 Pandemic. *Mass Communication and Society*: 1-26. <https://doi.org/10.1080/15205436.2024.2351980>

### 2023

3.  Bertero, A., **Scaduto, G.** A midsummer night's dream: political communication during the Italian 2022 electoral campaign. *Italian Journal of Electoral Studies* *QOE-IJES*, 86(1), 13-28. <https://doi.org/10.36253/qoe-14224>

### 2022

2.  **Scaduto, G.**, Mancosu, M. Lacrime di coccodrillo? Variazioni nel contenuto visuale su Instagram dei politici populisti e mainstream durante la pandemia. *Comunicazione Politica*, 23(2), 255-276. <https://www.rivisteweb.it/doi/10.3270/104851>

<!-- -->

1.  **Scaduto, G.** Gli algoritmi di computer vision: una guida all'uso per le scienze politiche e sociali. *Polis*, 36(2), 315-332. <https://www.rivisteweb.it/doi/10.1424/104525>

## Book chapters

### 2024

1.  Negri, F., **Scaduto, G.** Le «politologhe» e i «politologi» tra scienza e dibattito pubblico. In Verzichelli, L. La Scienza Politica Italiana, 50 anni dopo. Il Mulino.

## R&Rs/Under Review

-   **Scaduto, G.**, Negri, F., Decadri, S. Ideology at First Sight: A Comparative Study of Ideological Stereotypes in 4 European Countries. R&R in *International Journal of Public Opinion Research*.

<!-- -->

-   Goovaerts, I., Tsoulou-Malakoudi, A., **Scaduto, G.**, Feitosa, F., Lefevere, J. Divided Beyond Politics: How Perceptions of Non-Political Differences Are Linked to Affective Polarization Among Citizens. R&R in *Electoral Studies*.

<!-- -->

-   Tsoulou-Malakoudi, A., Goovaerts, I., **Scaduto, G.**, Van Erkel, P., Walgrave, S. Political others are perceived as non-politically different. R&R in *European Journal of Political Research*.

<!-- -->

-   Decadri, S., Negri, F., **Scaduto, G.** Visual Conjoint Experiments in Social-Scientific Research: A Semi-Systematic Review and a Protocol Blueprint for Cross-Country Applications. R&R in *Quality & Quantity*.

<!-- -->

-   **Scaduto, G.**, Valeriani, A. It Takes Two to Trust: Multi-modal Experimental Evidence of News Creators’ Influence on Trust-Based Decisions. Under Review in *International Journal of Press/Politics*.
    -   Preprint available [here](https://osf.io/preprints/socarxiv/tb6gh_v1)

<!-- -->

-   Negri, F., Decadri, S., **Scaduto, G.** A Visual Conjoint Experiment on Ideological Inferences from Politicians' Instagram Profiles. Under Review in *Political Behavior*.

<!-- -->

-   Valeriani, A., Garusi, D., **Scaduto, G.,** Splendore, S. News Efficacy as a Mediator between Expectations and Trust in Journalism. Empirical evidence from Italy. Under Review in *Communication Research*.

## Work-in-progress

<!-- -->

-   **Scaduto, G.**, Kemmers, R., de Koster, W. What does Climate Change Mean? A Focus Group Study in Italy.
    -   Submitted/In Submission
    -   Scheduled for presentation in *Dag van de Sociologie 2026*, *ASA 2026*

<!-- -->

-   **Scaduto, G.**, Nijs, T., de Koster, W., Negri, F. Network Heterogeneity in European Multiparty Contexts: Direct and Secondary Associations with Ideology-based Affective Evaluations.
    -   Submitted/In Submission
    -   Scheduled for presentation in *Dag van de Sociologie 2026*, *Politicologenetmaal 2026, ASA 2026*

<!-- -->

-   **Scaduto, G.** Chapter 11. Party Communication and the Role of Images (Visual Analysis). In Close, C., Legein, T. Researching party politics: Data, methods and (good) practices. Forthcoming in 2027.

<!-- -->

-   Negri, F., Decadri, S., **Scaduto, G.** A Visual Conjoint Experiment on Trust Dynamics Involving Politicians on Instagram.
    -   Submitted/In Submission

<!-- -->

-   **Scaduto, G.**, Bertero, A., Valeriani, A. AI and political communication, a correlational study in Italy.
    -   In writing

<!-- -->

## Datasets (publicly available)

2.  Political inferences from apolitical cues: food-based political inferences in Italy.
    -   **Scaduto, Gaetano [Producer]**. Negri, Fedra [Producer]. Mancosu, Moreno [Producer]. UniData - Bicocca Data Archive, Milan. Study Number SN248. Data file version 1.0 doi: [**10.71732/RMEP03**](https://doi.org/10.71732/RMEP03)

<!-- -->

1.  *Citizens and value of digital data*.
    -   Respi, Chiara [Producer]. Legnante, Guido [Producer]. Gui, Marco [Producer]. Pizzul, Dario [Producer]. Gaia, Alessandra [Producer]. Sala, Emanuela [Producer]. **Scaduto, Gaetano** **[Producer]**. UniData - Bicocca Data Archive, Milan. Study Number SN247. Data file version 1.0 [doi:10.20366/unimib/unidata/SN247-1.0](http://dx.doi.org/10.20366/unimib/unidata/SN247-1.0)

\bigskip \hrule

# Conferences, Workshops, and Seminars

25. European Consortium for Political Research (ECPR) Conference 2026, Krakow, Poland, 8-11 September 2026 (accepted, registered).

<!-- -->

24. 2026 Conference of the Italian Political Science Society (SISP). Trento, 3-5 September 2026 (accepted, registered).

<!-- -->

23. American Sociological Association Conference 2026. New York, United States, 7-11 August 2026 (accepted, registered).

<!-- -->

22. Politicologenetmaal 2026. Ghent, Belgium, 11-12 June 2026 (accepted, registered).

<!-- -->

21. Dag van de Sociologie 2026. Antwerp, Belgium, 26 May 2026 (accepted, registered).

<!-- -->

20. "'What Does Climate Change Mean?' A Focus Group study in Italy". Work in Progress Seminar Series. Collegio Carlo Alberto. Turin, Italy. 8 March 2026.

<!-- -->

19. "The Visual Politics of Populism". PRIN [Italian Ministry of University and Research grant] 2022 Final Event. Online event. 6 November 2025.

<!-- -->

18. 2025 Workshop Survey Experiments in the Social Sciences. Amsterdam Center for Inequality Studies (AMCIS). Amsterdam, The Netherlands. 1-2 October 2025.

<!-- -->

17. 2025 Conference of the Italian Political Science Society (SISP). Naples, 4-6 September 2025.

<!-- -->

16. European Consortium for Political Research (ECPR) Conference 2025, Thessaloniki, Greece, 26-29 August 2025.

<!-- -->

15. European Survey Research Association (ESRA) Conference 2025, Utrecht, The Netherlands, 14-18 July 2025.

<!-- -->

14. 2025 Conference of the Italian Political Communication Association (ASSOCOMPOL). Milan, 4-6 July 2025.

<!-- -->

13. European Political Science Association (EPSA) Conference 2025, Madrid, Spain, 26-28 June 2025.

<!-- -->

12. Politicologenetmaal 2025, Groningen, The Netherlands, 12-13 June 2025.

<!-- -->

11. PolMeth Europe 2025, London, UK, 7-9 April 2025.

<!-- -->

10. First MethodsNET Conference. Louvain-La-Neuve, Belgium, 31 October-1 November 2024.

<!-- -->

9.  2024 Workshop Survey Experiments in the Social Sciences. Amsterdam Center for Inequality Studies (AMCIS). Amsterdam, The Netherlands. 24 October 2024.

<!-- -->

8.  10th conference of the International Journal of Press/Politics. Edinburgh, 17-18 October 2024.

<!-- -->

7.  2024 Conference of the Italian Political Science Society (SISP). Trieste, 12-14 September 2024.
    -   Additionally chaired and organized two panels on "Survey Experiments in Political Science"

<!-- -->

6.  2024 Conference of the Italian Political Communication Association (ASSOCOMPOL). Catania, 30 May-1 June 2024.

<!-- -->

5.  2024 CompText Conference (COMPTEXT), Amsterdam, The Netherlands, 2-4 May 2024.

<!-- -->

4.  SPS Seminar: "Picturing Politics? Exploring the mental images of partisans and ideologues shaped by cultural consumption choices", University of Milan, 17 January 2024.

<!-- -->

3.  2023 Conference of the Italian Political Science Society (SISP). Genoa, 14-16 September 2023.

<!-- -->

2.  2023 Conference of the European Consortium for Political Research (ECPR). Prague, 4-8 September 2023.

<!-- -->

1.  2023 Conference of the Italian Political Communication Association (ASSOCOMPOL). Turin, 8-10 June 2023.

\bigskip \hrule

# Guest Lectures/Short Courses

7.  "Introduction to R". Crash course during the MetRiSP Crash Course Day. SISP 2026 Conference. Trento, 2 September 2026 (appointed).
    -   Teaching material is available [here](https://github.com/gaetanoscaduto/Crash_Course_R).

<!-- -->

6.  "How to replicate an experimental study?". Allievi program in Social and Political Sciences (Course of Applied Statistics to Social and Political Sciences), Collegio Carlo Alberto. Spring semester. 9 March 2026.

<!-- -->

5.  "Thinking about Politics". MA in Political Communication, University of Antwerp. Fall Semester, 2025.

<!-- -->

4.  "A practical introduction to the statistical software R for the analysis of electoral data". BA in Organization Sciences, University of Milan-Bicocca, Fall semester, 2023.
    -   Teaching material is available [here](https://github.com/gaetanoscaduto/teaching/tree/main/introduzioneR).

<!-- -->

3.  "Problems with collective decision-making: Condorcet’s paradox, strategic misreporting, and Arrow’s theorem". BA in Organization Sciences, University of Milan-Bicocca, Fall semester, 2023.
    -   Teaching material is available [here](https://github.com/gaetanoscaduto/teaching/tree/main/CondorcetPP).

<!-- -->

2.  "Political polarization and the state of the art regarding research on political inferences from apolitical cues". BA in Organization Sciences, University of Milan-Bicocca, Spring semester, 2023.
    -   You can download the slides [here](https://gaetanoscaduto.github.io/teaching_materials/Polarizzazione.pdf).

<!-- -->

1.  "An introduction to linear regression". BA in Organization Sciences, University of Milan-Bicocca, Spring semester, 2023.
    -   You can download the material I produced (a medium-length document presenting the general topic) [here](https://gaetanoscaduto.github.io/teaching_materials/Dispensa_regressione.pdf).

\bigskip \hrule

# Editorial Activities

## Reviewer for:

International Journal of Public Opinion Research, Quality & Quantity, Canadian Journal of Political Science, Comunicazione Politica.

\bigskip \hrule

# Media Outreach

## Radio

-   [Buongiorno InBlu 18/11/2025](https://www.play2000.it/detail/140?episode_id=25289&season_id=908), Radio InBlu 2000.
-   [Buongiorno InBlu 23/01/2025](https://www.radioinblu.it/streaming/?vid=0_4i5p4bw4), Radio InBlu 2000.
-   [Buongiorno InBlu 25/10/2024](https://www.radioinblu.it/streaming/?vid=0_onrwcs4r), Radio InBlu 2000.

## Online media

-   '["Bella Ciao! Het begin van het einde voor Meloni?](https://sampol.be/2026/05/bella-ciao-het-begin-van-het-einde-voor-meloni)'. Samenleving & Politiek. May 2026.


-   "[Talk-show politici, lo specchio di un’Italia polarizzata](https://lavoce.info/archives/106804/talk-show-politici-lo-specchio-di-unitalia-polarizzata/)" (with Negri F., in Italian)**.** LaVoce.info. January 2025.

<!-- -->

-   '["Ze zijn niet zoals wij": hoe kiezers kijken naar andere kiezers](https://www.sampol.be/2024/12/ze-zijn-niet-zoals-wij-hoe-kiezers-kijken-naar-andere-kiezers)' (with Tsoulou-Malakoudi, A. & Goovaerts, I., in Dutch). Samenleving & Politiek. December 2024.

<!-- -->

-   "[What your menu choice says about your politics](https://theloop.ecpr.eu/what-your-menu-choice-says-about-your-politics/)" (with Negri F.). The Loop. October 2024.

<!-- -->

-   "[Dimmi cosa mangi e ti dirò che partito voti](https://lavoce.info/archives/106171/dimmi-cosa-mangi-e-ti-diro-che-partito-voti/)" (with Negri F., in Italian)**.** LaVoce.info. October 2024.

\bigskip \hrule

# Awards, Grants, and Memberships

## Awards

-   **Best paper from a Junior Researcher 2023**
    -   Awarded by the Italian Political Communication Association (ASSOCOMPOL) for the best paper presented in the 2023 conference. The prize refers to "*Food for (political) thought: investigating factors and behaviors associated with political inferences from apolitical cues in Italy*" (with F. Negri)

## Grants and Scholarships

-   **Conference Fee Waiver for the International Journal of Press/Politics 2024 conference** - 300£

-   **"Mini-scholarship"** **to take part in the 2024 Conference.** Italian Political Science Association (SISP) - 200€

-   **Ph.D. Scholarship** University of Milan Bicocca, Department of Sociology and Social Research - 16,243.00€ per year for three years

-   **Ph.D. Scholarship** University of Trento, Department of Sociology and Social Research (Declined to accept Ph.D. scholarship at UNIMIB)

-   **Scholarship - Excellence Project 2022**, Department of Culture, Politics and Society - University of Turin - 1500€

-   **Study prize 2021**, Renato Einaudi University College of Turin - 1500€

-   **Study prize 2019**, Renato Einaudi University College of Turin - 2500€

-   **Scholarship by EDISU Piemonte (Regional Agency for Educational Rights) 2021**. Awarded through the combination of (higher) academic performance and (lower) parental income - 5100€

-   **Scholarship by EDISU Piemonte (Regional Agency for Educational Rights) 2020**. Awarded through the combination of (higher) academic performance and (lower) parental income - 5100€

-   **Scholarship by EDISU Piemonte (Regional Agency for Educational Rights) 2019**. Awarded through the combination of (higher) academic performance and (lower) parental income - 5100€

-   **Scholarship by EDISU Piemonte (Regional Agency for Educational Rights) 2018**. Awarded through the combination of (higher) academic performance and (lower) parental income - 5100€

-   **Scholarship by EDISU Piemonte (Regional Agency for Educational Rights) 2017**. Awarded through the combination of (higher) academic performance and (lower) parental income - 5100€

## Memberships

-   Member of ASSOCOMPOL (Italian Political Communication Association) [Since 2024]

-   Member of SISP, (Società Italiana di Scienza Politica - Italian Political Science Society) [Since 2023]

-   Member of ECPR Affective Polarization Standing Group [Since 2023]

    \bigskip \hrule

# Other professional experiences

## Academic

<!-- -   **Research Collaborator,** *University of Antwerp*, Belgium \hfill Feb 2024-Present -->

<!--     -   Involvement in the activities related to the “NotLikeUS" project. [See here for details](https://notlikeus.be/). -->

-   **Research Collaborator,** *University of Milan-Bicocca*, Italy \hfill Sep 2023-Aug 2025

    -   Involvement in the activities related to the project “VIPOP - The visual politics of populism” (PI: Mattia Zulianello, UniTS; Vice PIs: Fedra Negri, Unimib; Luigi Curini, Unimi). These activities included (but were not limited to):
        a)  Designing a survey fielded in 4 European countries

        b)  Designing survey experiments

        c)  Working with computational methods to download and analyze politicians' social media posts

        d)  Managing the relationship between the working group and the survey company

        e)  Supervising the translation and cultural adaptation of the survey in multiple national contexts

-   **Research Collaborator**, *University of Milan-Bicocca*, Italy \hfill Aug-Dec 2023

    -   Analysis and management of survey data for research purposes for the project "VDATA - The Value of Digital Data"

-   **Conference Assistant**, *European Survey Research Association,* Milan, Italy \hfill Jul 2023

    -   Assisted in the activities related to the 2023 European Survey Research Association Conference.

-   **Research Fellow**, *Collegio Carlo Alberto*, Turin \hfill May-Jun 2022

    -   Data gathering on the media outlets of 47 countries with research purposes. Data analysis on survey results (Stata, R). Data entry and data management (Excel).

## Extra-academic

-   **Junior Research Specialist and Deputy Campaign Coordinator**, *Social Changes, Inc.,* Rome, Italy \hfill 2022

    a)  Contributed to organizing and coordinating multiple campaigns for the 2022 political and municipal elections in Italy.
    b)  Managed the relationship with companies providing media analysis services (WebPredict) and provided insights on how to use media analysis for strategic purposes during the campaign.
    c)  Coordinated and conducted research on advertisements and media profiles of adversarial campaigns.
    d)  Created electoral databases useful for electoral insights (R). Provided training on digital strategies (WhatsApp-Telegram Cascades) to staff members of multiple campaigns.
    e)  Coordinated and wrote a daily newsletter, including press reviews and campaign insights with strategic consideration.
    f)  Contributed to the construction of targets for social media political advertisements.

-   **Part-Time Receptionist**, *Renato Einaudi University College*, Turin \hfill 2021-2022

    -   Supervised on the general life and activity of the college. Front office relations. Management of relations with the administration of the college and maintenance, cleaning, and organizational figures.

-   **Students' Tutor**, *Renato Einaudi University College*, Turin \hfill 2021-2022

    -   Mediation between the college administration and its students. Conflict resolution. Support in first arrival orientation. Management of students' educational plan.

        \bigskip \hrule

# Skills

## Languages

-   **Italian**, Native.
-   **English**, C2.
-   **Dutch**, C1 speaking, B2 writing, exam for C1 writing scheduled for June 2026.

## Coding Skills/Softwares

-   **R**, Advanced; **C**, Proficient; **SQL**, Proficient; **LaTex**, Proficient; **Microsoft Office package**, Proficient; **Python**, Intermediate; **C++**, Beginner; **Stata**, Beginner; **Html**, Beginner; **Shiny**, Beginner; **Javascript**, Beginner; **Matlab**, Beginner

    \bigskip \hrule

# Academic References

-   **Willem de Koster**. Erasmus University Rotterdam. [dekoster\@essb.eur.nl](mailto:dekoster@essb.eur.nl){.email}

-   **Stefaan Walgrave**. University of Antwerp. stefaan.walgrave\@uantwerpen.be

If not available, feel free to contact:

<!-- -   **Augusto Valeriani**. University of Bologna. augusto.valeriani\@unibo.it -->

-   **Delia Baldassarri**. New York University. delia.b\@nyu.edu

-   **Fedra Negri**. University of Milan Bicocca. fedra.negri\@unimib.it

-   **Moreno Mancosu**. University of Turin. moreno.mancosu\@unito.it

```{r, message=F, echo=F, warning=F, results='hide'}
# RUN THIS TO UPDATE ALSO IN WEBSITE!

#rmarkdown::render('C:/Users/gasca/OneDrive - Erasmus University Rotterdam/Dottorato/CV/cv/cv_pdf/cv.Rmd', output_file = 'C:/Users/gasca/OneDrive - Erasmus University Rotterdam/Dottorato/Website/academic_cv.pdf')
```
