---
title: "CV"
author: "Gaetano Scaduto"
output:
  pdf_document:
    latex_engine: pdflatex
    template: "C:/Users/gasca/OneDrive - Università degli Studi di Milano-Bicocca/Dottorato/CV/cv/svm-latex-cv.tex"
  html_document:
    df_print: paged
geometry: margin=1.1in
jobtitle: Ph.D Student in Analysis of Social and Economic Processes
fontawesome: yes
email: gaetano.scaduto@unimib.it
web: "gaetanoscaduto.quarto.pub/home/"
updated: yes
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 10pt
linkcolor: blue
urlcolor: blue
---

<!-- -->

# **Education**

## Ph.D Student in Analysis of Social and Economic Processes \hfill Nov 2022-present

-   *University of Milan-Bicocca*, Milan, Italy

## Visiting Ph.D Student \hfill Feb 2024-present

-   *University of Antwerp*, Antwerp, Belgium
-   Supervisor: Stefaan Walgrave
-   Collaborating in the activities of the ["Media, Movement and Politics" (M2P)](https://www.uantwerpen.be/en/research-groups/m2p/) research group and the [NOTLIKEUS](https://notlikeus.be/) project

## Master's Degree in Political and Public Communication \hfill Sep 2020-July 2022

-   *University of Turin*, Turin, Italy
-   Final grade: 110/110 with honors, special mention, and rights of publication

## Bachelor's Degree in Mathematics for Engineering \hfill Sep 2017-Jul 2020

-   *Polytechnic University of Turin*, Turin, Italy
-   Final grade: 110/110

# Summer Schools, Winter Schools, and Short Courses

## The Summer Institutes in Computational Social Science, University of Bologna \hfill  June 2024

-   2-weeks summer school on computational methods, with competitive selection process.

## Essex Summer School in Social Science Data Analysis, University of Essex \hfill  Jul-Aug 2023

-   *Confirmatory Factor Analysis and Structural Equation Modeling* \hfill Essex, UK


## Essex Summer School in Social Science Data Analysis, University of Essex \hfill  Jul-Aug 2023

-   *Causal Inference and Experiments in Social Sciences* \hfill Essex, UK

## SISP - Italian Political Science Society \hfill  Sep. 2023

-   *Crash Course in Text Analysis* \hfill Genoa, Italy

    \bigskip \hrule

# Publications and Conferences

## Papers published in peer-reviewed journals

-   Mancosu, M., **Scaduto, G**. "Crowds and Smiles: Visual Opportunity Structures and the Communication of European Political Leaders During the COVID-19 Pandemic." Mass Communication and Society (2024): 1-26.

-   Bertero, A., **Scaduto, G.** (2023). A midsummer night's dream: political communication during the Italian 2022 electoral campaign. Italian Journal of Electoral Studies QOE-IJES. <https://doi.org/10.36253/qoe-14224>

-   **Scaduto, G.**, Mancosu, M. (2022). Lacrime di coccodrillo? Variazioni nel contenuto visuale su Instagram dei politici populisti e mainstream durante la pandemia. Comunicazione politica, 23(2), 255-276. <https://www.rivisteweb.it/doi/10.3270/104851>

-   **Scaduto, G.** (2022). Gli algoritmi di computer vision: una guida all'uso per le scienze politiche e sociali. Polis, 36(2), 315-332. <https://www.rivisteweb.it/doi/10.1424/104525>


## Conferences Papers, Activities, and Seminars[^1]

[^1]: Asterisks signal the paper presenter

-   2024 *Conference of the Italian Political Communication Association (ASSOCOMPOL). Catania, 30 May-1 June*.
    -   Negri, F., **Scaduto, G\***. The Pundit Paradox: Exploring the Mismatch between Supply and Demand in Italian Political Talk Show Guests.

<!-- -->

-   2024 *CompText Conference* *(COMPTEXT)*, Amsterdam, 2-4 May.
    -   **Scaduto, G.**\*, Decadri, S., Mancosu, M., Negri, F. Analyzing Visual Communication Strategies: A Comparative Study of Populist and Mainstream Political Parties on Instagram Across 28 European Countries (2019-2021).

<!-- -->

-   *SPS Seminar: "Picturing Politics? Exploring the mental images of partisans and ideologues shaped by cultural consumption choices", University of Milan, 17 January 2024.*

    -   **Scaduto, G.\***, Negri, F. Food for (political) thought: exploring the factors associated with making political inferences from apolitical cues in Italy

<!-- -->

-   *2023 Conference of the Italian Political Science Society (SISP). Genoa, 14-16 September.*
    -   **Scaduto, G.\***, Negri, F. Food for (political) thought: exploring the factors associated with making political inferences from apolitical cues in Italy.
    -   Mancosu, M., **Scaduto, G.\*** Crowds and smiles: Visual opportunity structures and the communication of European political leaders during the Covid-19 pandemic

<!-- -->

-   *2023 VDATA Final Conference. Pavia, 7-8 September.*
    -   Respi, C.\*, Gui, M., Legnante, G., **Scaduto, G.**, Serini, M., Pizzul, D., & Gerosa, T. Privacy protection as an exception in the digital inequality framework (and why this is not good news)

<!-- -->

-   *2023 Conference of the European Consortium for Political Research (ECPR). Prague, 4-8 September.*
    -   **Scaduto, G.\***, Negri, F. Food for (political) thought: exploring the factors associated with making political inferences from apolitical cues in Italy.

<!-- -->

-   *2023 Conference of the Italian Political Communication Association (ASSOCOMPOL). Turin, 8-10 June.*
    -   **Scaduto, G.\***, Negri, F. Food for (political) thought: exploring the factors associated with making political inferences from apolitical cues in Italy.

<!-- -->

-   *2022 Conference of the Italian Political Communication Association (ASSOCOMPOL). Bologna June 30th-July 1st.*

    -   Mancosu, M.\*, **Scaduto, G.** The representation of political leaders in times of pandemic crisis. Evidence from 28 European countries.

# Teaching

## Tutor in Mathematics \hfill Nov 2023-July 2024 - 30 hours

-   *University of Milan-Bicocca*, Milan, Italy. 

## Tutor in Public Policies \hfill Oct 2023-July 224 - 40 hours

-   *University of Milan-Bicocca*, Milan, Italy. 

## Subject Expert in Public Policies \hfill Dec 2022-present 
-   *University of Milan-Bicocca*, Milan, Italy

    \bigskip \hrule

# Awards 

-   **Best paper from a Junior Researcher 2023**
    -   Awarded by the Italian Political Communication Association (ASSOCOMPOL) for the best paper presented in the 2023 conference. The prize refers to "*Food for (political) thought: investigating factors and behaviors associated with political inferences from apolitical cues in Italy*" (with F. Negri)
-   **"Mini-scholarship"** **to take part in the 2024 Conference.** Italian Political Science Association (SISP)SISP - 200€
-   **Scholarship - Excellence's Project 2022**, Department of Culture, Politics and Society - University of Turin - 1500€
-   **Study's prize 2021**, Renato Einaudi University College of Turin - 1500€
-   **Study's prize 2019**, Renato Einaudi University College of Turin - 2500€
-   **Scholarship by EDISU Piemonte (Regional Agency for Educational Rights) 2017, 2018, 2019, 2020, 2021**. Awarded through the combination of (higher) academic performance and (lower) parental income - 25000€ (over 5 years)


# Other professional experiences

## Academic

-   **Research Collaborator** *University of Antwerp*, Belgium \hfill Feb 2024-Present
    -   Involvement in the activities related to the project “NotLikeUS" project. [See here for details](https://notlikeus.be/).
-   **Research Collaborator,** *Univesity of Milan-Bicocca*, Italy \hfill Sept 2023-Aug 2025
    -   Involvement in the activities related to the project “The visual politics of populism” (PI: Mattia Zulianello, UniTS; Vice PIs: Fedra Negri, Unimib; Luigi Curini, Unimi). 
-   **Research Collaborator**, *University of Milan-Bicocca*, Italy \hfill Aug-Dec 2023
    -   Analysis and management of survey data for research purposes for the project VDATA - The Value of Digital Data
-   **Conference Assistant**, *European Survey Research Association* \hfill Jul 2023
    -   Assisted in the activities related to the 2023 European Survey Research Association Conference.
-   **Research Fellow**, *Collegio Carlo Alberto*, Turin \hfill May-June 2022
    -   Data gathering on the media outlets of 47 countries with research purposes. Data analysis on survey results (Stata, R). Data entry and data management (Excel)

## Extra-academic

-   **Junior Research Specialist and Deputy Campaign Coordinator**, *Social Changes, Inc.* \hfill 2022

    -   Contributed to organizing and coordinating multiple campaigns for the 2022 political and municipal elections in Italy. 


# Skills

## Languages

-   **Italian**, *mother tongue*
-   **English**, C1, certified in 2019 (IELTS 7.5); C2, self-evaluated, 2024
-   **Dutch,** A1 (certified in August 2024)

## Coding Skills/Softwares

-   **R**, Advanced; **C**, Proficient; **SQL**, Proficient; **LaTex**, Proficient; **Microsoft Office package**, Proficient; **Python**, Intermediate; **C++**, Beginner; **Stata**, Beginner; **Html**, Beginner; **Javascript**, Beginner; **Matlab**, Beginner

```{r, message=F, echo=F, warning=F, results='hide'}
# RUN THIS TO UPDATE ALSO IN WEBSITE!

#rmarkdown::render('C:/Users/gasca/OneDrive - Università degli Studi di Milano-Bicocca/Dottorato/CV/cv/cv_pdf/cv.Rmd', output_file = 'C:/Users/gasca/OneDrive - Università degli Studi di Milano-Bicocca/Dottorato/Website/cv.pdf')
```
